use deployer signer in deployments scripts
alchemistcoin/aludel-factory pull request #36
Opened 2022-11-17 16:38 UTC by itirabasso

hardhat defaults to index 0 account when no signer is specified, which breaks local changes in the hardhat config.

2022-11-30 20:25 UTC, plaintextpaco requested changes
I don't quite get what is that is breaking due to the deployment files not having the deployer address set explicitly, could you elaborate on that?

also, I see there are other calls to `getContractAddress` where the signer is not set explicitly:
- [ ] deploy/AludelV2.ts:21
- [ ] deploy/Programs.ts:20

Is it possible that you only fixed those that broke in a particualr deploy run, but you had some contracts already deployed?

2022-11-30 20:31 UTC, plaintextpaco commented
additionally
- the `run lint-ts` commit only changes what was just modified on its parent commit, so it should've been an ammend to that one
- why import the `getNamedAccount` function explicitly, instead of getting it from the parameters from the deploy function? (I'm not sure if that's exactly the same, but in the examples the instance passed as a parameter is always used: https://github.com/wighawag/hardhat-deploy#an-example-of-a-deploy-script-)

2023-01-08 21:37 UTC, plaintextpaco commented
@itirabasso any updates on this? should we close it?

2023-01-16 19:34 UTC, itirabasso commented
Let's close it.

2023-01-16 19:34 UTC, closed without merging